# Structured ADA 2026 knowledge base, carried over from the R demo
# (ada_guideline_knowledge_base_demo.html). Same three layers: text
# chunks, medication table, rule registry. This is the source data
# for the vector index - add Figure 9.4 / remaining tables here once
# they're extracted.

TEXT_CHUNKS = [
    {
        "chunk_id": "ADA2026_REC_9_7_ASCVD_GLP1_SGLT2",
        "recommendation_id": "9.7",
        "source_page": 8,
        "condition": "ASCVD or high CVD risk",
        "drug_class": "GLP-1 RA; SGLT2 inhibitor",
        "action_type": "include",
        "rule_strength": "strong_recommend",
        "text": "For type 2 diabetes with established or high ASCVD risk, include a GLP-1 RA and/or SGLT2 inhibitor with cardiovascular benefit irrespective of A1c.",
    },
    {
        "chunk_id": "ADA2026_REC_9_8_HF_SGLT2",
        "recommendation_id": "9.8",
        "source_page": 8,
        "condition": "Heart failure",
        "drug_class": "SGLT2 inhibitor",
        "action_type": "recommend",
        "rule_strength": "strong_recommend",
        "text": "For type 2 diabetes with heart failure, recommend an SGLT2 inhibitor for glycemic management and prevention of HF hospitalization irrespective of A1c.",
    },
    {
        "chunk_id": "ADA2026_REC_9_10_CKD_SGLT2_GLP1",
        "recommendation_id": "9.10",
        "source_page": 8,
        "condition": "CKD",
        "drug_class": "SGLT2 inhibitor; GLP-1 RA",
        "action_type": "use",
        "rule_strength": "strong_recommend",
        "text": "For type 2 diabetes with CKD, use an SGLT2 inhibitor or GLP-1 RA with demonstrated benefit for glycemic management, CKD progression, and cardiovascular event reduction.",
    },
    {
        "chunk_id": "ADA2026_REC_9_11_ADV_CKD_GLP1",
        "recommendation_id": "9.11",
        "source_page": 8,
        "condition": "Advanced CKD",
        "drug_class": "GLP-1 RA",
        "action_type": "prefer",
        "rule_strength": "strong_recommend",
        "text": "For type 2 diabetes with advanced CKD, GLP-1 RA is preferred for glycemic management because of lower hypoglycemia risk and cardiovascular benefit.",
    },
    {
        "chunk_id": "ADA2026_REC_9_18_DPP4_GLP1_AVOID",
        "recommendation_id": "9.18",
        "source_page": 10,
        "condition": "Medication combination",
        "drug_class": "DPP-4 inhibitor; GLP-1 RA",
        "action_type": "avoid",
        "rule_strength": "hard_avoid_if_combined",
        "text": "Concurrent DPP-4 inhibitor use with GLP-1 RA or dual GIP/GLP-1 RA is not recommended because it adds no glucose-lowering benefit.",
    },
    {
        "chunk_id": "ADA2026_REC_9_20_INSULIN_SEVERE_HYPERGLYCEMIA",
        "recommendation_id": "9.20",
        "source_page": 10,
        "condition": "Severe hyperglycemia",
        "drug_class": "insulin",
        "action_type": "consider",
        "rule_strength": "preference_sensitive",
        "text": "Insulin initiation should be considered when symptoms are present or A1c/glucose levels are very high.",
    },
    {
        "chunk_id": "ADA2026_REC_9_21_GLP1_BEFORE_INSULIN",
        "recommendation_id": "9.21",
        "source_page": 10,
        "condition": "Injectable therapy",
        "drug_class": "GLP-1 RA",
        "action_type": "prefer",
        "rule_strength": "strong_recommend",
        "text": "Without severe hyperglycemia or crisis, GLP-1-based therapy is preferred to insulin for initial or add-on glucose-lowering therapy.",
    },
    {
        "chunk_id": "ADA2026_REC_9_22_GLP1_WITH_INSULIN",
        "recommendation_id": "9.22",
        "source_page": 10,
        "condition": "Insulin combination",
        "drug_class": "GLP-1 RA; insulin",
        "action_type": "combine_or_reassess",
        "rule_strength": "strong_recommend",
        "text": "If insulin is used, GLP-1 RA combination is recommended for glycemic effectiveness and benefits on weight and hypoglycemia risk; insulin dosing should be reassessed.",
    },
    {
        "chunk_id": "ADA2026_METFORMIN_EGFR_RATIONALE",
        "recommendation_id": None,
        "source_page": 15,
        "condition": "Kidney function",
        "drug_class": "metformin",
        "action_type": "avoid_or_caution",
        "rule_strength": "hard_avoid",
        "text": "Metformin is generally safe at eGFR >=30; risk rises when eGFR is below 30, and eGFR 30-45 warrants caution.",
    },
]

# ADA Table 9.2 - drug class properties, one row per class
MEDICATION_TABLE = [
    {
        "drug_class": "metformin",
        "glycemic_efficacy": "high",
        "hypoglycemia_risk": "no",
        "weight_effect": "neutral/modest loss",
        "heart_failure_effect": "neutral",
        "ckd_progression_effect": "neutral",
        "kidney_dosing_consideration": "contraindicated with eGFR <30",
        "major_cautions": "GI intolerance; vitamin B12 deficiency",
    },
    {
        "drug_class": "SGLT2 inhibitor",
        "glycemic_efficacy": "intermediate to high",
        "hypoglycemia_risk": "no",
        "weight_effect": "loss",
        "heart_failure_effect": "benefit for selected agents",
        "ckd_progression_effect": "benefit for selected agents",
        "kidney_dosing_consideration": "glucose-lowering effect reduced at eGFR <45; may start/continue for cardiorenal benefit if eGFR >20",
        "major_cautions": "DKA risk; genital infections; UTI; volume depletion",
    },
    {
        "drug_class": "GLP-1 RA",
        "glycemic_efficacy": "high to very high",
        "hypoglycemia_risk": "no",
        "weight_effect": "loss",
        "heart_failure_effect": "benefit for semaglutide SQ",
        "ckd_progression_effect": "kidney endpoint benefit for selected agents",
        "kidney_dosing_consideration": "no dose adjustment for dulaglutide/liraglutide/semaglutide; monitor kidney function with severe GI reactions",
        "major_cautions": "GI effects; pancreatitis concern; gallbladder disease; retinopathy monitoring",
    },
    {
        "drug_class": "dual GIP/GLP-1 RA",
        "glycemic_efficacy": "very high",
        "hypoglycemia_risk": "no",
        "weight_effect": "loss, very high",
        "heart_failure_effect": "benefit for tirzepatide",
        "ckd_progression_effect": "potential benefit",
        "kidney_dosing_consideration": "no dose adjustment; monitor kidney function with severe GI reactions",
        "major_cautions": "GI effects; pancreatitis concern; gallbladder disease",
    },
    {
        "drug_class": "DPP-4 inhibitor",
        "glycemic_efficacy": "intermediate",
        "hypoglycemia_risk": "no",
        "weight_effect": "neutral",
        "heart_failure_effect": "neutral/potential saxagliptin risk",
        "ckd_progression_effect": "neutral",
        "kidney_dosing_consideration": "renal dose adjustment for sitagliptin/saxagliptin/alogliptin; not linagliptin",
        "major_cautions": "pancreatitis reports; joint pain; bullous pemphigoid",
    },
    {
        "drug_class": "pioglitazone/TZD",
        "glycemic_efficacy": "high",
        "hypoglycemia_risk": "no",
        "weight_effect": "gain",
        "heart_failure_effect": "increased HF risk",
        "ckd_progression_effect": "neutral",
        "kidney_dosing_consideration": "generally not recommended in kidney impairment due to fluid retention",
        "major_cautions": "fluid retention/HF; fracture risk; bladder cancer caution",
    },
    {
        "drug_class": "sulfonylurea",
        "glycemic_efficacy": "high",
        "hypoglycemia_risk": "yes",
        "weight_effect": "gain",
        "heart_failure_effect": "neutral",
        "ckd_progression_effect": "neutral",
        "kidney_dosing_consideration": "glyburide generally not recommended in CKD; glipizide/glimepiride conservative initiation",
        "major_cautions": "hypoglycemia risk; CV warning based on older sulfonylurea",
    },
    {
        "drug_class": "insulin",
        "glycemic_efficacy": "high to very high",
        "hypoglycemia_risk": "yes",
        "weight_effect": "gain",
        "heart_failure_effect": "neutral",
        "ckd_progression_effect": "neutral",
        "kidney_dosing_consideration": "lower doses required as eGFR decreases; titrate clinically",
        "major_cautions": "injection reactions; hypoglycemia risk increases with kidney impairment",
    },
]

# Decision rule registry - human-readable trigger logic derived from
# Figure 9.4 and the recommendations above
RULE_REGISTRY = [
    {
        "rule_id": "ADA2026_RULE_METFORMIN_EGFR_LT30",
        "trigger_logic": "egfr_ml_min_1_73m2 < 30",
        "drug_class": "metformin",
        "expected_action": "avoid_or_stop",
        "expected_dose_label": "do_not_use",
        "rule_strength": "hard_avoid",
        "supporting_chunk_ids": "ADA2026_METFORMIN_EGFR_RATIONALE",
    },
    {
        "rule_id": "ADA2026_RULE_METFORMIN_EGFR_GE30_BASELINE",
        "trigger_logic": "egfr_ml_min_1_73m2 >= 30 and baseline_metformin",
        "drug_class": "metformin",
        "expected_action": "continue_allowed_or_renal_caution",
        "expected_dose_label": "same_or_reduced_dose",
        "rule_strength": "caution",
        "supporting_chunk_ids": "ADA2026_METFORMIN_EGFR_RATIONALE",
    },
    {
        "rule_id": "ADA2026_RULE_HF_SGLT2I",
        "trigger_logic": "heart_failure",
        "drug_class": "SGLT2 inhibitor",
        "expected_action": "recommend",
        "expected_dose_label": "standard_starting_dose_if_eligible",
        "rule_strength": "strong_recommend",
        "supporting_chunk_ids": "ADA2026_REC_9_8_HF_SGLT2",
    },
    {
        "rule_id": "ADA2026_RULE_CKD_SGLT2I_OR_GLP1RA",
        "trigger_logic": "ckd_or_albuminuria and sglt2i_eligible_by_egfr",
        "drug_class": "SGLT2 inhibitor",
        "expected_action": "recommend_or_consider",
        "expected_dose_label": "standard_starting_dose_if_eligible",
        "rule_strength": "strong_recommend",
        "supporting_chunk_ids": "ADA2026_REC_9_10_CKD_SGLT2_GLP1",
    },
    {
        "rule_id": "ADA2026_RULE_ADVANCED_CKD_GLP1RA",
        "trigger_logic": "advanced_ckd",
        "drug_class": "GLP-1 RA",
        "expected_action": "prefer_or_consider",
        "expected_dose_label": "standard_starting_dose",
        "rule_strength": "strong_recommend",
        "supporting_chunk_ids": "ADA2026_REC_9_11_ADV_CKD_GLP1",
    },
    {
        "rule_id": "ADA2026_RULE_ASCVD_GLP1RA",
        "trigger_logic": "ascvd",
        "drug_class": "GLP-1 RA",
        "expected_action": "consider",
        "expected_dose_label": "standard_starting_dose",
        "rule_strength": "strong_recommend",
        "supporting_chunk_ids": "ADA2026_REC_9_7_ASCVD_GLP1_SGLT2",
    },
    {
        "rule_id": "ADA2026_RULE_ASCVD_SGLT2I",
        "trigger_logic": "ascvd",
        "drug_class": "SGLT2 inhibitor",
        "expected_action": "consider",
        "expected_dose_label": "standard_starting_dose_if_eligible",
        "rule_strength": "strong_recommend",
        "supporting_chunk_ids": "ADA2026_REC_9_7_ASCVD_GLP1_SGLT2",
    },
    {
        "rule_id": "ADA2026_RULE_OBESITY_MASH_GLP1RA",
        "trigger_logic": "obesity or mash_or_masld",
        "drug_class": "GLP-1 RA",
        "expected_action": "consider",
        "expected_dose_label": "standard_starting_dose",
        "rule_strength": "preference_sensitive",
        "supporting_chunk_ids": "ADA2026_REC_9_7_ASCVD_GLP1_SGLT2",
    },
    {
        "rule_id": "ADA2026_RULE_DPP4_WITH_GLP1_AVOID",
        "trigger_logic": "glp1_expected and baseline_dpp4i",
        "drug_class": "DPP-4 inhibitor",
        "expected_action": "stop_or_avoid",
        "expected_dose_label": "do_not_use_with_glp1",
        "rule_strength": "hard_avoid_if_combined",
        "supporting_chunk_ids": "ADA2026_REC_9_18_DPP4_GLP1_AVOID",
    },
    {
        "rule_id": "ADA2026_RULE_A1C_GT10_INSULIN_CONSIDER",
        "trigger_logic": "severe_hyperglycemia",
        "drug_class": "insulin",
        "expected_action": "consider",
        "expected_dose_label": "individualized",
        "rule_strength": "preference_sensitive",
        "supporting_chunk_ids": "ADA2026_REC_9_20_INSULIN_SEVERE_HYPERGLYCEMIA",
    },
    {
        "rule_id": "ADA2026_RULE_INSULIN_ADV_CKD_CAUTION",
        "trigger_logic": "baseline_insulin and advanced_ckd",
        "drug_class": "insulin",
        "expected_action": "dose_caution_or_deintensify",
        "expected_dose_label": "individualized_lower_dose_possible",
        "rule_strength": "caution",
        "supporting_chunk_ids": "ADA2026_REC_9_22_GLP1_WITH_INSULIN",
    },
    {
        "rule_id": "ADA2026_RULE_PRANDIAL_INSULIN_SIMPLE_REGIMEN",
        "trigger_logic": "baseline_prandial_insulin and simple_regimen_preference",
        "drug_class": "prandial insulin",
        "expected_action": "consider_deintensification",
        "expected_dose_label": "individualized",
        "rule_strength": "preference_sensitive",
        "supporting_chunk_ids": "ADA2026_REC_9_5_PERSON_CENTERED",
    },
]
